alert("YESS!! It is!")
alert("LLOLL")
alert("You will get this pop us again and again")
alert("I am True")
alert("OK")
alert("AHhhh")
alert("DO you know?")
alert("Something?")
alert("I don't")
alert("")
alert("")
alert("")
alert("")
alert("")
alert("")
alert("")
alert("")
alert("You Got Gutts?")
